parameters:
#    admin.example.class: Xiucai\AdminBundle\Example
    PagePaginationServices.class: Xiucai\AdminBundle\Services\PagePaginationServices

services:
#    admin.example:
#        class: %admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    PagePaginationServices:
          class:        %PagePaginationServices.class%
          arguments:
              entityManager: "@doctrine.orm.entity_manager"