biye_page:
    resource: "@BiyePageBundle/Resources/config/routing.yml"
    prefix:   /

biye_admin:
    resource: "@BiyeAdminBundle/Resources/config/routing.yml"
    prefix:   /

biye_store:
    resource: "@BiyeStoreBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
