Xiucai\StoreBundle\Entity\XcConferencePrivacy:
    type: entity
    table: xc_conference_privacy
    id:
        id:
            type: smallint
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 16
            fixed: false
            comment: 直播间隐私类型
    lifecycleCallbacks: {  }
