Xiucai\StoreBundle\Entity\XcConferenceStatus:
    type: entity
    table: xc_conference_status
    id:
        id:
            type: smallint
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 16
            fixed: false
            comment: 直播间状态类型
    lifecycleCallbacks: {  }
