Xiucai\StoreBundle\Entity\XcMembershipInventory:
    type: entity
    table: xc_membership_inventory
    id:
        id:
            type: bigint
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        memberId:
            type: bigint
            nullable: true
            unsigned: true
            comment: '用户ID（对应*_member的ID）'
            column: member_id
        serviceId:
            type: bigint
            nullable: true
            unsigned: true
            comment: 会员服务ID
            column: service_id
        serviceLevel:
            type: smallint
            nullable: true
            unsigned: true
            comment: 会员服务等级
            column: service_level
        quantity:
            type: smallint
            nullable: true
            unsigned: true
            comment: 数量
        createTime:
            type: datetime
            nullable: true
            comment: 创建时间
            column: create_time
        startDate:
            type: date
            nullable: true
            comment: 服务开始时间
            column: start_date
        endDate:
            type: date
            nullable: true
            comment: 服务结束时间
            column: end_date
        isActivate:
            type: smallint
            nullable: true
            unsigned: true
            comment: 是否有效
            column: is_activate
    lifecycleCallbacks: {  }
